### ISSUE TITLE
"Error opening file: Value too large for defined data type" on big otrkey

### ISSUE THREAD

**Issue by MisterEffiks** [otrtool/otrtool#11]
Hi,

i've a problem with 2 large otrkeys (2.3 and 2.6 GB), otrtool shows this error:

Error opening file: Value too large for defined data type.

otrtool @ Zyxel NSA325v2

Edit: that's weird, it works on a odroid xu4 without any problems...

Thanks,
MrFX

**Comment by Jonny007-MKD** [comment]
You hit the 2GB limit.
otrtool needs to change some stuff to make large files work. I found some infos on:

    __USE_LARGEFILE
    use fseeko64 and ftello64 (although the problem here is already fopen)

**Comment by eshrdlu** [comment]
@MisterEffiks: Could you post output of `make`, please?

On a Linux machine, it should look like this:
`
$ make clean
rm -f src/md5.o src/main.o otrtool otrtool.1.gz
$ make
cc  -O3 -Wall -Wextra -g -DVERSION='"v1.2.0-3-gd86b39e"' **-D_LARGEFILE_SOURCE** **-D_FILE_OFFSET_BITS=64** -c src/md5.c -o src/md5.o
...
`

**Comment by MisterEffiks** [comment]
Thanks, i've added it by hand and now it works.
There was no LFS definition during build process.
