### ISSUE TITLE
Must be multiple of 8...

### ISSUE THREAD

**Issue by linsus** [otrtool/otrtool#5]
While trying to decoder newer files, the pyropeter otrtool simply doesn't get a valid response from server. The request sent to server is different (in length and content) to the from otrdecoder. The response returned is very short approx. 224 bytes and does contain 0x27 bytes of payload. 
As a result, the decryption is aborted.
So, where's is the problem? Older recordings are still working well, also elder version of otrdecoder tools with these new files.
Would be glad for a fix. otrtool is the old sw running on my NAS, easily decoding the files, without copying from a to b and back to a.
Thanks, and keep up the good work.
linsus

**Comment by Jonny007-MKD** [comment]
I am currently having problems with empty responses (HTTP Status 200).
When sniffing the Windows OTR Decoder 2.0.0.22 I noticed they are using "TIGER Library" as User Agent.
But as the responses are empty after this request, too, I cannot confirm if the request would be working with this UA.
