### ISSUE TITLE
decrypt not working

### ISSUE THREAD

**Issue by treaki** [otrtool/otrtool#7]
hi,

i have used this tool before on another pc, now ive redownloadet and recompiled it on another pc and it isnt working anymore. Possibly they changed the server interface... Can you check that and confirm or deny that this is a problem in the interface between this tool and the otr servers? If that so can you fix it.

```
treaki@treakis-xxxx:~/Videos$ otrtool -e xxxx -p xxxx -x Der_satirische_Jahresrueckblick_2014_14.12.28_23-00_3sat_30_TVOON_DE.mpg.HQ.avi.otrkey 
OTR-Tool, v1.0.2-13-ga465ed7
Trying to contact server...
Server responded.
Length of response must be a multiple of 8.00000000  E7 D0 81 07 6D F7 00 00  F9 E3 8E 85 E3 6D 34 F0  |....m........m4.|
00000010  40 7C DF 40 02 0F 4F 03  13 5D B8 DF BF 7A E3 C0  |@|.@..O..]...z..|
00000020  B7 04 40 05 04 2D 38                              |..@..-8         |
00000027

Server response is unuseable, exiting
treaki@treakis-xxxx:~/Videos$ 

```

Thanks and greetings

**Comment by Jonny007-MKD** [comment]
Hi, 

you're right:
Problem: #5
Merge request: #6

Greetz

**Comment by treaki** [comment]
ok. so do i understand that right that this repository is dead and i should switch into eshrdlu's one?

thanks in advance

**Comment by treaki** [comment]
ok, i have now added eshrdlus repro to my local git remotes fetched and merged it into my local repo and build. its working thanks.

in detail:

```
 1996  cd ~/build/
 1999  cd otrtool/

 2009  git remote add eshrdlu_otrtool https://github.com/eshrdlu/otrtool
 2010  git fetch
 2012  git branch -a
 2013  git fetch eshrdlu_otrtool
 2014  git branch -a
 2016  git merge remotes/eshrdlu_otrtool/master
 2017  gitk
```

![bildschirmfoto](https://cloud.githubusercontent.com/assets/1477872/5811431/3fddbf72-a057-11e4-9050-83e396ee2e07.png)

**Comment by eshrdlu** [comment]
No no, it was not dead, it was... resting. ;)

**Comment by treaki** [comment]
all right, thanks
